export const AREAS = ['Transformación Digital', 'Corsusa International S.A.C.',
    'Gerencia General, Dpto. de Administración Financiera, Dpto. Administración y Logística, Dpto. Recursos Humanos, Comité HSL, EPS, Dpto. QHSE',
    'Dpto. TD, Marketing, Dpto. Ventas, Dpto. Servicios, Dpto. Proyectos, Gerencia General Adjunta',
    'Corsusa International S.A.C., UN AI\n',
    'Dpto. de Administración Financiera', 'Dpto. Servicios, Servicios',
    'Dpto. Servicios', 'Dpto. Ventas Internas', 'Servicios',
    'Dpto. QHSE, EPS', 'Corsusa International S.A.C., UN AI',
    'Logística, Almacén y Distribución',
    'Proyectos de Instalación y construcción',
    'Almacén y Distribución',
    'Comité HSL, EPS, Comité SST, Operaciones', 'UN AU', 'EPS, UN AI',
    'UN VA', 'UN AI', 'Comité HSL, Dpto. QHSE, Comité SST',
    'Contabilidad y Finanzas', 'Comité HSL, EPS, Dpto. Ventas',
    'Comité SST, UN AI', 'Logística', 'EPS, UN VA',
    'Contabilidad y Finanzas, EPS',
    'Logística, Compras Locales e Importaciones, EPS, Comité SST',
    'Comité HSL, Servicios', 'Comité HSL, UN VA',
    'Comité HSL, Marketing', 'RRHH, Comité HSL, EPS',
    'Contabilidad y Finanzas, Credito y Cobranzas, Facturacion, EPS',
    'EPS, UN AU', 'Compras Locales e Importaciones',
    'Gerencia General Adjunta', 'TBR', 'Externos',
    'Comité HSL, UN AU', 'Dpto. Proyectos',
    'Dpto. Ventas Internas, UN VA',
    'Corsusa International S.A.C., Dpto. Servicios',
    'Corsusa International S.A.C., Proyectos de Instalación y construcción',
    'Corsusa International S.A.C., Dpto. Ventas Internas',
    'Dpto. QHSE', 'RRHH, Comité HSL',
    'Corsusa International S.A.C., Dpto. TD', 'Contabilidad',
    'Proyectos',
    'Otro'
]